apiVersion: v1
kind: Service
metadata:
  name: nico-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

  type: NodePort
